module.exports = {
  apps: [
    {
      name: 'zyra',
      cwd: __dirname,
      script: 'dist/index.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '5G',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        WA_API_ENABLED: 'true',
        WA_API_HOST: '127.0.0.1',
        WA_API_PORT: '3021',
        WA_BOOTSTRAP_CONNECTIONS_ENABLED: 'true',
        WA_HISTORY_SYNC_INITIAL_BOOTSTRAP: 'true',
        WA_HISTORY_SYNC_ON_NEW_LOGIN: 'true',
        WA_HISTORY_IMPORT_ENABLED: 'false',
        WA_GROUP_SYNC_ON_CONNECT: 'false',
        WA_APPEND_MESSAGE_IMPORT_ENABLED: 'false',
        WA_WEBHOOK_RETRY_ENABLED: 'false',
        WA_WEBHOOK_OUTBOX_ENABLED: 'false',
        WA_MYSQL_CONNECTION_LIMIT: '5',
        WA_MYSQL_MAX_IDLE: '2',
        WA_MYSQL_QUEUE_LIMIT: '100',
        WA_SQL_STORE_CONCURRENCY: '2',
        WA_SQL_EVENT_LOG_ENABLED: 'false',
        WA_SQL_MESSAGE_EVENTS_ENABLED: 'false',
        WA_SIGNAL_KEYS_CHUNK: '100',
        WA_AUTH_DISK_CONCURRENCY: '4',
        WA_MEDIA_AUTO_DOWNLOAD: 'false',
        WA_MEDIA_MAX_BYTES: '536870912',
        WA_COMMAND_TIMEOUT_MS: '30000',
        WA_ROUTER_MAX_PENDING_PER_QUEUE: '100',
        WA_MAX_CACHED_MESSAGES: '1000',
        // Para subir várias sessões fixas no mesmo processo, injete WA_CONNECTION_IDS via ambiente.
        // Exemplo: WA_CONNECTION_IDS=default,loja1,loja2
        // Para pairing dinâmico via terminal + descoberta no próximo restart, deixe WA_CONNECTION_IDS ausente.
        WA_ANTIBAN_ENABLED: 'true',
        WA_ANTIBAN_DEAF_SESSION_ENABLED: 'true',
        WA_ANTIBAN_DEAF_SESSION_TIMEOUT_MS: '300000',
        WA_ANTIBAN_DEAF_SESSION_MIN_UPTIME_MS: '120000',
        WA_ANTIBAN_DEAF_SESSION_AUTO_RECONNECT: 'true',
        WA_ANTIBAN_METRICS_ENABLED: 'false',
        WA_ANTIBAN_METRICS_HOST: '0.0.0.0',
        WA_ANTIBAN_METRICS_PORT: '9108',
        WA_ANTIBAN_METRICS_PATH: '/metrics',
      },
    },
    {
      name: 'zyra-api-webhook',
      cwd: __dirname,
      script: 'dist/index.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '5G',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        WA_API_ENABLED: 'true',
        WA_API_HOST: '127.0.0.1',
        WA_API_PORT: '3020',
        WA_BOOTSTRAP_CONNECTIONS_ENABLED: 'false',
        WA_WEBHOOK_RETRY_ENABLED: 'false',
        WA_WEBHOOK_OUTBOX_ENABLED: 'false',
        WA_WEBHOOK_TIMEOUT_MS: '5000',
        WA_WEBHOOK_MAX_ATTEMPTS: '2',
        WA_WEBHOOK_OUTBOX_BATCH_SIZE: '10',
        WA_SQL_EVENT_LOG_ENABLED: 'false',
        WA_SQL_MESSAGE_EVENTS_ENABLED: 'false',
      },
    },
    {
      name: 'zyra-backfill',
      cwd: __dirname,
      script: 'dist/core/db/backfill.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '5G',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        WA_BACKFILL_ONCE: 'false',
        WA_BACKFILL_INTERVAL_MS: '300000',
        WA_BACKFILL_BATCH_SIZE: '100',
        WA_BACKFILL_MAX_PASSES: '5',
        WA_BACKFILL_MAX_FAILURES: '3',
      },
    },
  ],
}
