module.exports = {
  apps: [
    {
      name: 'zyra',
      cwd: __dirname,
      script: 'dist/index.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        WA_API_ENABLED: 'true',
        WA_API_HOST: '127.0.0.1',
        WA_API_PORT: '3021',
        WA_BOOTSTRAP_CONNECTIONS_ENABLED: 'true',
        WA_HISTORY_SYNC_INITIAL_BOOTSTRAP: 'true',
        WA_HISTORY_SYNC_ON_NEW_LOGIN: 'true',
        WA_HISTORY_IMPORT_ENABLED: 'false',
        WA_GROUP_SYNC_ON_CONNECT: 'false',
        WA_APPEND_MESSAGE_IMPORT_ENABLED: 'false',
        WA_WEBHOOK_RETRY_ENABLED: 'false',
        WA_WEBHOOK_OUTBOX_ENABLED: 'false',
        // Para subir várias sessões fixas no mesmo processo, injete WA_CONNECTION_IDS via ambiente.
        // Exemplo: WA_CONNECTION_IDS=default,loja1,loja2
        // Para pairing dinâmico via terminal + descoberta no próximo restart, deixe WA_CONNECTION_IDS ausente.
        WA_ANTIBAN_ENABLED: 'true',
        WA_ANTIBAN_DEAF_SESSION_ENABLED: 'true',
        WA_ANTIBAN_DEAF_SESSION_TIMEOUT_MS: '300000',
        WA_ANTIBAN_DEAF_SESSION_MIN_UPTIME_MS: '120000',
        WA_ANTIBAN_DEAF_SESSION_AUTO_RECONNECT: 'true',
        WA_ANTIBAN_METRICS_ENABLED: 'true',
        WA_ANTIBAN_METRICS_HOST: '0.0.0.0',
        WA_ANTIBAN_METRICS_PORT: '9108',
        WA_ANTIBAN_METRICS_PATH: '/metrics',
      },
    },
    {
      name: 'zyra-api-webhook',
      cwd: __dirname,
      script: 'dist/index.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        WA_API_ENABLED: 'true',
        WA_API_HOST: '127.0.0.1',
        WA_API_PORT: '3020',
        WA_BOOTSTRAP_CONNECTIONS_ENABLED: 'false',
        WA_WEBHOOK_RETRY_ENABLED: 'true',
        WA_WEBHOOK_OUTBOX_ENABLED: 'true',
      },
    },
    {
      name: 'zyra-backfill',
      cwd: __dirname,
      script: 'dist/core/db/backfill.js',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        WA_BACKFILL_ONCE: 'false',
      },
    },
  ],
}
